### ISSUE TITLE
Datas

### ISSUE THREAD

**Issue by hasaiki123** [weisting-sinica/Python-Kriging-Climate#1]
Where can I find the datastets？
Can you give it to me？

**Comment by Irish-kw** [comment]
This project not able to provide data. 


寄件者: "hasaiki123" <notifications@github.com> 
收件者: "weisting-kw/Python-Kriging-Climate" <Python-Kriging-Climate@noreply.github.com> 
副本: "Subscribed" <subscribed@noreply.github.com> 
寄件備份: 2020 9 月 17 星期四 上午 10:28:42 
主旨: [weisting-kw/Python-Kriging-Climate] Datas (#1) 





Where can I find the datastets？ 
Can you give it to me？
